baseURL = 'https://wecore.ir/'
canonifyURLs = false
relativeURLs = true
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false  # keep fa at root
title = 'وِی‌کُر | WECORE'
hasCJKLanguage = true  # good for Persian layout handling
enableRobotsTXT = true
publishDir = "docs"

#[permalinks]
#    about-us             = "/:section/:contentbasename/"
#    blog                = "/:section/:year/:month/:title/"
#    apply                 = "/:section/:contentbasename/"
#    something_else                = "/:title/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]

[languages.fa]
languageName = "فارسی"
weight = 1
title = "وِی‌کُر"
languageCode = "fa"
contentDir = "content/fa"
# you can have separate menus, etc.
[languages.fa.params]
  direction = "rtl"

[languages.en]
languageName = "English"
weight = 2
title = "WECORE"
languageCode = "en"
contentDir = "content/en"

############################
[[cascade]]
   [cascade._target]
    path = '/features/coming-soon'
    [cascade.params]
      layout = "coming-soon"
